spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devdesk
    username: devdesk_user
    password: devdesk_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  docker:
    compose:
      enabled: false

server:
  port: 8080

app:
  jwt:
    secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration: 86400000
